default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mybakery
  password: 15600
  host: localhost
  port: 5432

development:
  <<: *default
  database: LetsHangOut_development

test:
  <<: *default
  database: LetsHangOut_test

production:
  <<: *default
  database: LetsHangOut_production